### ISSUE TITLE
could you report performance of your implementation?

### ISSUE THREAD

**Issue by PkuRainBow** [dichotomies/proxy-nca#1]
Hi, great work. I am wondering whether it is possible for you to share the performance of your method.

Regards

**Comment by dichotomies** [comment]
Hi, thanks, I'm glad you like my work!

You can find the preliminary results in the two notebooks of this repository, e.g. [Cars196](https://github.com/dichotomies/proxy-nca/blob/deeba4c6c96ad5ce98352652f96d544490b9f81e/pnca-cars.ipynb) and [CUB](https://github.com/dichotomies/proxy-nca/blob/deeba4c6c96ad5ce98352652f96d544490b9f81e/pnca-cub.ipynb) (including R@k for k = 1, 2, 4, 8 and NMI).

There's still a lot of room for improvement (I hope). For example using RMSProp with the gamma = 0.94 as described in the paper. So, I'm still fine-tuning it.

You could check out the notebook in the next weeks. I'll update the results after some more experiments.

**Comment by bnulihaixia** [comment]
OK, the result mean you have not used the pre-trained model, or used the pre-trained model in a wrong way.

**Comment by dichotomies** [comment]
Hey, I was busy with another project in the last months. Anyway, I've finished it. I'm getting about the same results as in the paper with the same network (Inception V2).
