### ISSUE TITLE
function pairwise_distance

### ISSUE THREAD

**Issue by Chen94yue** [dichotomies/proxy-nca#13]
Why the implementation of function pairwise_distance is too complex and cost many GPU memory? In my opinion, this function is equivalent to:
D = 18 - 2 * torch.mm(X, P.t())

**Comment by dichotomies** [comment]
I guess there's not only one way to implement `pairwise_distance`. Especially, if considering computation stability. Feel free to create a pull request, if you get the same results within less computing time with this implementation.
