### ISSUE TITLE
could you report performance of you implementation on Cars196 and SOP?

### ISSUE THREAD

**Issue by youmingdeng** [dichotomies/proxy-nca#9]
Hi, i have clone your code, and the performance on CUB is
R@1: 51.5
R@2: 63.9
R@4: 73.7
R@8: 82.3
but the R@1 on Cars196 Up to 60.0
the paper result: R@1 on Cars196 is 73.2

**Comment by dichotomies** [comment]
Hi, nice to hear that it's working out for CUB so well.

I've recently tried out the code for Cars and got somewhat the same performance as you. I fixed the issue and will upload the new code soon -- probably by end of this week. With this fix the results should be the same as in the paper.

Thanks for reporting your results.

**Comment by 945984093** [comment]
Thank you very much!
I have read this paper recently. The best result in the paper is the use of static proxies Assignment, but in this code the proxies is changed in training process. 
I have already sent an email to the author. If I receive a reply, I will let you know.

**Comment by youmingdeng** [comment]
@dichotomies  Hi，how is your effect?
The author replied to my mail，he used the proxies are initialized using xavier initialization and the dynamic proxies are changed during training.

**Comment by ifeherva** [comment]
I am also trying to reproduce the results on Cars196, my implementation yields the same results as mentioned above. @dichotomies What needs to be changed to get that performance? I can PR it if you dont have time.

**Comment by dichotomies** [comment]
@ifeherva @youmingdeng I'm currently working on it. There was some issue with the servers I'm working on till beginning of January, but it's fixed now. I'm planning to get it done by end of this week.

**Comment by dichotomies** [comment]
@sunbaigui Hey, I've updated the repository. I'm getting nearly the same results for Cars, but I only had time to try out a few learning rates, so probably one might get higher results with the right settings (just like for CUB).
